### ISSUE TITLE
Limit of 16 light sources with shadows. 

### ISSUE THREAD

**Issue by Iknowyou808** [Facepunch/sandbox#31] opened 2021-10-12 14:44 UTC
Will the limit of 16 light sources with shadows be corrected in the future, at the moment this limit reaches 16, will it be more? 32/64/128 or more.

**Comment by bellum128** [comment] 2021-12-28 01:29
Duplicate of https://github.com/Facepunch/sbox-issues/issues/1035 on the proper sbox issues page.

I have also been pushing for this change.

**Closed** 2022-07-31 05:55 UTC
